// We need to work around Step numbers here if we are going to potentially exclude the AMI subscription

=== Sign in to your AWS account

. Sign in to your AWS account at https://aws.amazon.com with an IAM user role that has the necessary permissions. For more information, see
//TODO Planning_the_deployment anchor link does not resolve.
 link:#planning-the-deployment[Planning the deployment], earlier in this guide.
. Ensure that your AWS account is configured correctly, as discussed in the
//TODO Technical_requirements anchor link does not resolve.
 link:#technical-requirements[Technical requirements] section.
. Use the Region selector in the navigation bar to choose the AWS Region where you want to deploy Amazon EKS.
. Choose the key pair that you created earlier. In the navigation pane of the https://console.aws.amazon.com/ec2/[Amazon EC2 console^], choose *Key Pairs*, and then choose your key pair from the list.

=== Launch the Quick Start

. Optionally, if you want to configure advanced parameters, launch the https://fwd.aws/6dEQ7[advanced configuration template^].
. Choose one of the following options to launch the AWS CloudFormation template into your AWS account. For help with choosing an option, see link:#_deployment_options[Deployment options], earlier in this guide.
[cols=",",",]
|===
|{launch_new_vpc}[Deploy Armory Enterprise into a new VPC^]
|===
Deployment takes {deployment_time} to complete, depending on the parameter values you choose.

//NOTE: If you deploy Amazon EKS into an existing VPC, ensure that your VPC has private subnets in different Availability Zones for the workload instances. The subnets require egress internet access using a NAT gateway or an HTTP proxy. If you want to use the Kubernetes integration with Elastic Load Balancing, you must tag each private subnet with `kubernetes.io/role/internal-elb=true` and each public subnet with `kubernetes.io/role/elb=true`.

[start=3]
. Check the Region that’s displayed in the upper-right corner of the navigation bar, and change it if necessary. This is where the network infrastructure for Amazon EKS is built. The template launches in the US East (Ohio) Region by default.
+
NOTE: Some services are not supported in all AWS Regions. For a current list of supported Regions, see https://docs.aws.amazon.com/general/latest/gr/eks.html[Amazon Elastic Kubernetes Service endpoints and quotas^].
+
[start=4]
. On the *Select template* page, keep the default setting for the template URL, and then choose *Next*.
. On the *Specify stack details* page, change the stack name if needed. Review the parameters for the template, and provide values for any parameters that require input. For all other parameters, review the default settings, and customize them as necessary.
+
NOTE: If Amazon EKS is already deployed in your account, ensure that the `Per account shared resources` parameter is set to *No*. If you deploy a new Amazon EKS instance in the same Region as a previously deployed instance, set `Per region shared resources` to *No*.
+
NOTE: If you created and intend to use an advanced configuration stack, ensure that you set the value for `Config set name` to match the value you used when you launched the advanced configuration stack.